### PR TITLE
Show backend region on ping response from GCLB

### PR DESCRIPTION
**Pull request by kkr16**
This change enables the Global External HTTPS Load Balancer endpoint to show the region it is using as a backend.

We currently use `mode: no-cors` and ignoring CORS issues, at the cost of making any cross-origin request opaque to javascript; so we can't read the region name from the response.

Removing it means we're now reverting to default `mode: cors`, only accepting cross-origin requests that adhere to CORS standards.

Our /api/ping endpoint [code](https://github.com/kkr16/gcping/blob/93b5e5e4a702dcdbaf4690cf445dc0be85dde6bf/internal/httphandler/httphandler.go#L98-L102) already includes the header Access-Control-Allow-Origin: *, allowing any origin, thus satisfying CORS constraints.

Before:
image

After:
image

PR staged at: https://pr-137-us-central1-5tkroniexa-uc.a.run.app/

### CODE REVIEW

**Review by enocom — COMMENTED** [review]
Would you mind elaboring how removing the CORS constraint makes this possible?

**Comment by kkr16** [comment]
> Would you mind elaboring how removing the CORS constraint makes this possible?

By using `mode: no-cors` we're ignoring CORS issues, at the cost of making any cross-origin request opaque to javascript; so we can't read the region name from the response.

Removing it means we're now reverting to default `mode: cors`, only accepting cross-origin requests that adhere to CORS standards.

Our `/api/ping` endpoint [code](https://github.com/kkr16/gcping/blob/93b5e5e4a702dcdbaf4690cf445dc0be85dde6bf/internal/httphandler/httphandler.go#L98-L102)  already includes the header `Access-Control-Allow-Origin: *`, allowing  any origin, thus satisfying CORS constraints.

**Comment by enocom** [comment]
Let's add that to the commit message for future maintainers.

**Comment by kkr16** [comment]
> Let's add that to the commit message for future maintainers.

@enocom - done! 
Also added to the PR description for visibility. 
Thanks for the review. :)

**Review by enocom — APPROVED** [review]

**Comment by enocom** [comment]
Thanks for the nice commit message!

**Pull request merged**
