### PR TITLE
Update regions.json

### PR DESCRIPTION
**Pull request by 444B**
added africa-south1, which is now publicly GA

### CODE REVIEW

**Comment by crwilcox** [comment]
Do you have a press release stating this? We've announced this region as future, but I can't select it in my cloud console yet, and the region documentation shows it as a future region yet.

image

**Comment by 444B** [comment]
@crwilcox 
Thanks for the rapid response and the query
Yes, I am able to see the region in GCE from my cloud console, screenshot attached 
Screenshot 2024-01-26 193526
I would not have made the PR if this was only available on pantheon but it seems to be public

Also available in Cloud Run if that matters for gcping

Please let me know if that is sufficient to add africa-south1 to gcping. 
Since it is a new region and the first one in the continent, it could make a big difference to many customers (about 1.4B) in Africa that would benefit from the lowered latency and choose GCP for their solutions

**Comment by crwilcox** [comment]
It seems like some projects have access, while others don't at this time. `gcping` has access, but my experimental project doesn't for instance.

image

We'll hold this until the launch as sometimes in this early state things are a bit unknown, and I'd rather not mislead customers for them to find out they couldn't turn up here yet. We should be properly launching soon.

**Comment by 444B** [comment]
@crwilcox 
It seems like we have announced the region today
https://cloud.google.com/blog/products/infrastructure/heita-south-africa-new-cloud-region

**Comment by crwilcox** [comment]
Yep, it was scheduled for today. I'll get this merged :)

**Pull request merged**
